config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :games

   root 'home#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :creator, class_name: "User"
  belongs_to :participant, class_name: "User"
  
  def players
    [creator, participant]
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  
  def new
    render 'new'
  end
  
  def create
     creator = User.find_or_create_by(name: "PJ")
    @game = Game.create(creator_id: creator.id) 
    redirect_to @game    
  end
  
  def show
    @game = Game.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController 

  def index
    redirect_to new_game_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/new.html.haml
= link_to "New Game", games_path,method: :post

app/views/games/show.html.haml
.board
  .divider
  .top
    .quarter.top-left<>
      - 6.times do
        .point>
    .quarter.top-right<>
      - 6.times do
        .point>
  .bottom
    .quarter.bottom-left<>
      - 6.times do
        .point>
    .quarter.bottom-right<>
      - 6.times do
        .point>
.rhs-action       
  .left
    %p.current-user
  %a.roll_dice{href: '#'} Roll Dice
  %form.auto_role
    %input{type: 'checkbox', name: 'auto_role'}
    %label auto role?
  %p.dice-1
  %p.dice-2
  
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Basicgammon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>